*Trabajo Práctico Nro1 - Primer Encuentro con la EPH*

- Grupo 5 del curso "M73 13 Seminarios Optativos - Taller de Programación"
- Integrantes: Santiago Caballero Yver, Oriana Valentina Gegena y Valeria Eliana Gonzalez.

In [4]:
!pip install openpyxl pandas
# Cargamos librerias a utilizar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker


# Cargamos bases de datos T424 y T425:
T424 = pd.read_excel('C:/Users/gegen/OneDrive/Documentos/2. Economía Aplicada/Programación/usu_individual_T424.xlsx')
T425 = pd.read_excel('C:/Users/gegen/OneDrive/Documentos/2. Economía Aplicada/Programación/usu_individual_T425.xlsx')

Requirement already satisfied: openpyxl in c:\users\gegen\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: pandas in c:\users\gegen\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: et-xmlfile in c:\users\gegen\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\gegen\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gegen\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gegen\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gegen\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\gegen\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
# Variables de interés a utilizar en el analisis
variables = [
    "CODUSU", "ANO4", "TRIMESTRE", "NRO_HOGAR", "PONDERA", 
    "CH04", "CH06", "CH07", "CH08", "NIVEL_ED", 
    "ESTADO", "CAT_OCUP", "EMPLEO", "SECTOR", 
    "PP04C", "PP04D_COD", "P21", "P47T", 
    "PP07H", "PP3E_TOT"
]

T424_v = T424[variables].copy()
T425_v = T425[variables].copy()
    
# Variables incluidas:
# "PP07H"     Descuento jubilatorio (formalidad asalariada)
# "PP3E_TOT"  Horas trabajadas (salario horario)

#Seguimiento de variables:
#CH04 - Varón/Mujer
#CH06 - edad
#CH07 - Estado civil
#CH08 - Cobertura salud
#PP04C - Cantidad de personas que trabajan en el establecimiento
#PP04D_COD - Codigo de ocupación
#P21 - ingreso de la ocupación principal
#P47T - Ingreso total individual

In [7]:
# Resumen descriptivo de las bases para observar posibles outliers
resumen_2024 = T424_v.describe().T
resumen_2025 = T425_v.describe().T

# Mostramos el resultado del 2024
print("Resumen estadístico EPH - Cuarto Trimestre 2024:")
display(resumen_2024) 

# Mostramos el resultado del 2025
print("\nResumen estadístico EPH - Cuarto Trimestre 2025:")
display(resumen_2025)

Resumen estadístico EPH - Cuarto Trimestre 2024:

,count,mean,std,min,25%,50%,75%,max
ANO4,46860.0,2024.000000,0.000000,2024.0,2024.0,2024.0,2024.0,2024.0
TRIMESTRE,46860.0,4.000000,0.000000,4.0,4.0,4.0,4.0,4.0
NRO_HOGAR,46860.0,1.034550,0.634871,1.0,1.0,1.0,1.0,72.0
PONDERA,46860.0,635.586278,824.688160,23.0,180.0,315.0,663.0,7989.0
CH04,46860.0,1.519718,0.499616,1.0,1.0,2.0,2.0,2.0
CH06,46860.0,36.759112,22.182034,-1.0,18.0,35.0,54.0,103.0
CH07,46860.0,3.521618,1.651600,1.0,2.0,5.0,5.0,9.0
CH08,46860.0,2.134998,1.869091,1.0,1.0,1.0,4.0,123.0
NIVEL_ED,46860.0,3.780644,1.756795,1.0,3.0,4.0,5.0,7.0
ESTADO,46860.0,2.181946,1.133963,0.0,1.0,3.0,3.0,4.0
CAT_OCUP,46860.0,1.272407,1.398353,0.0,0.0,0.0,3.0,9.0
EMPLEO,21132.0,1.437110,0.537083,1.0,1.0,1.0,2.0,9.0
SECTOR,21132.0,1.685122,1.619249,1.0,1.0,1.0,2.0,9.0
PP04C,21132.0,17.045287,31.625792,0.0,1.0,6.0,10.0,99.0
PP04D_COD,21132.0,45003.543820,23037.143929,1.0,30313.0,41332.0,58113.0,99999.0
P21,46860.0,226549.710649,476388.472311,-9.0,0.0,0.0,300000.0,15000000.0
P47T,46804.0,327037.717567,536816.879202,-9.0,0.0,100000.0,500000.0,16500000.0
PP07H,21132.0,0.986987,0.734547,0.0,0.0,1.0,2.0,2.0
PP3E_TOT,21132.0,37.868588,46.836761,0.0,25.0,40.0,48.0,999.0

Resumen estadístico EPH - Cuarto Trimestre 2025:

,count,mean,std,min,25%,50%,75%,max
ANO4,43703.0,2025.000000,0.000000,2025.0,2025.0,2025.0,2025.0,2025.0
TRIMESTRE,43703.0,4.000000,0.000000,4.0,4.0,4.0,4.0,4.0
NRO_HOGAR,43703.0,1.039311,0.840685,1.0,1.0,1.0,1.0,71.0
PONDERA,43703.0,687.200993,905.356807,24.0,192.0,342.0,724.0,7954.0
CH04,43703.0,1.525639,0.499348,1.0,1.0,2.0,2.0,2.0
CH06,43703.0,37.586573,22.326015,-1.0,19.0,36.0,55.0,101.0
CH07,43703.0,3.513946,1.649546,1.0,2.0,5.0,5.0,9.0
CH08,43703.0,2.159714,1.768585,1.0,1.0,1.0,4.0,23.0
NIVEL_ED,43703.0,3.751504,1.737705,1.0,3.0,4.0,5.0,7.0
ESTADO,43703.0,2.168021,1.121546,0.0,1.0,3.0,3.0,4.0
CAT_OCUP,43703.0,1.270531,1.392975,0.0,0.0,0.0,3.0,9.0
EMPLEO,19698.0,1.448066,0.525115,1.0,1.0,1.0,2.0,9.0
SECTOR,19698.0,1.678089,1.577366,1.0,1.0,1.0,2.0,9.0
PP04C,19698.0,17.686415,32.556840,0.0,1.0,6.0,10.0,99.0
PP04D_COD,19698.0,44960.441111,23023.383802,1.0,30312.0,41332.0,57314.0,99999.0
P21,43703.0,331263.130517,701873.611098,-9.0,0.0,0.0,500000.0,30000000.0
P47T,43638.0,474936.457422,808649.455832,-9.0,0.0,180000.0,700000.0,30000000.0
PP07H,19698.0,0.968169,0.742635,0.0,0.0,1.0,2.0,2.0
PP3E_TOT,19698.0,38.012184,47.829056,0.0,25.0,40.0,48.0,999.0

In [10]:
# Reemplazamos los datos correspondientes a NS/NC a NaN
def reemplazar_nsnc_por_nan(df):
    df_clean = df.copy()

    # Variables categóricas donde 9 es NS/NC
    vars_cat = ['CAT_OCUP', 'EMPLEO', 'SECTOR', 'CH07']
    for col in vars_cat:
        df_clean[col] = df_clean[col].replace(9, np.nan)
        
    # Códigos específicos de NS/NC del INDEC
    df_clean['PP3E_TOT'] = df_clean['PP3E_TOT'].replace(999, np.nan)     # Horas
    df_clean['PP04C'] = df_clean['PP04C'].replace(99, np.nan)            # Tamaño empresa
    df_clean['PP04D_COD'] = df_clean['PP04D_COD'].replace(99999, np.nan) # Ocupación
    df_clean['ESTADO'] = df_clean['ESTADO'].replace(0, np.nan)           # Entrevista no realizada
    
    # Valores "0" que significan "No corresponde"
    df_clean.loc[df_clean['CAT_OCUP'] == 0, 'CAT_OCUP'] = np.nan
    df_clean.loc[df_clean['PP07H'] == 0, 'PP07H'] = np.nan
    
    # Ingresos: Cualquier valor <= 0 (incluyendo el -9 de NS/NC) pasa a NaN
    df_clean.loc[df_clean['P21'] <= 0, 'P21'] = np.nan
    df_clean.loc[df_clean['P47T'] <= 0, 'P47T'] = np.nan

    # ---------------------------------------------------------
    # Limpieza outliers:
    # ---------------------------------------------------------
    
    # Nos quedamos estrictamente con la Población en Edad de Trabajar (PET)
    df_clean = df_clean[df_clean['CH06'] >= 15]

    # Límite físico humano de horas trabajadas (tope conservador)
    df_clean.loc[df_clean['PP3E_TOT'] > 120, 'PP3E_TOT'] = np.nan
    
    # Trimming (recorte) del 1% superior de la distribución de ingresos
    if df_clean['P21'].notna().sum() > 0:
        q99_p21 = df_clean['P21'].quantile(0.99)
        df_clean.loc[df_clean['P21'] > q99_p21, 'P21'] = np.nan
        
    if df_clean['P47T'].notna().sum() > 0:
        q99_p47t = df_clean['P47T'].quantile(0.99)
        df_clean.loc[df_clean['P47T'] > q99_p47t, 'P47T'] = np.nan
        
    return df_clean

# Aplicamos la limpieza a las bases
T424_v = reemplazar_nsnc_por_nan(T424_v)
T425_v = reemplazar_nsnc_por_nan(T425_v)

In [11]:
# Repetimos resumen descriptivo de las bases para observar posibles outliers ya sin los NS/NC
resumen_2024 = T424_v.describe().T
resumen_2025 = T425_v.describe().T

# Mostramos el resultado del 2024
print("Resumen estadístico EPH - Cuarto Trimestre 2024:")
display(resumen_2024) 

# Mostramos el resultado del 2025
print("\nResumen estadístico EPH - Cuarto Trimestre 2025:")
display(resumen_2025)

Resumen estadístico EPH - Cuarto Trimestre 2024:

,count,mean,std,min,25%,50%,75%,max
ANO4,37889.0,2024.000000,0.000000,2024.0,2024.0,2024.0,2024.0,2024.0
TRIMESTRE,37889.0,4.000000,0.000000,4.0,4.0,4.0,4.0,4.0
NRO_HOGAR,37889.0,1.033730,0.698977,1.0,1.0,1.0,1.0,72.0
PONDERA,37889.0,609.624614,778.611442,23.0,174.0,307.0,648.0,7989.0
CH04,37889.0,1.527303,0.499261,1.0,1.0,2.0,2.0,2.0
CH06,37889.0,43.586555,18.999866,15.0,27.0,42.0,58.0,103.0
CH07,37888.0,3.171558,1.653192,1.0,2.0,3.0,5.0,5.0
CH08,37889.0,2.079020,1.902164,1.0,1.0,1.0,4.0,123.0
NIVEL_ED,37889.0,3.913484,1.437338,1.0,3.0,4.0,5.0,7.0
ESTADO,37839.0,1.850340,0.972010,1.0,1.0,1.0,3.0,3.0
CAT_OCUP,22074.0,2.699647,0.536641,1.0,2.0,3.0,3.0,4.0
EMPLEO,21114.0,1.431373,0.495280,1.0,1.0,1.0,2.0,2.0
SECTOR,20273.0,1.375968,0.612710,1.0,1.0,1.0,2.0,3.0
PP04C,18421.0,4.994083,3.787705,0.0,1.0,5.0,8.0,12.0
PP04D_COD,21117.0,44972.025098,23003.409184,1.0,30313.0,41332.0,58113.0,99998.0
P21,16099.0,586009.684825,417043.237960,2000.0,280000.0,500000.0,800000.0,2000000.0
P47T,24113.0,556475.711981,396984.597075,1000.0,295000.0,450000.0,780000.0,2000000.0
PP07H,15290.0,1.363898,0.481136,1.0,1.0,1.0,2.0,2.0
PP3E_TOT,21082.0,35.839294,16.250082,0.0,25.0,40.0,48.0,118.0

Resumen estadístico EPH - Cuarto Trimestre 2025:

,count,mean,std,min,25%,50%,75%,max
ANO4,35784.0,2025.000000,0.000000,2025.0,2025.0,2025.0,2025.0,2025.0
TRIMESTRE,35784.0,4.000000,0.000000,4.0,4.0,4.0,4.0,4.0
NRO_HOGAR,35784.0,1.039571,0.924262,1.0,1.0,1.0,1.0,71.0
PONDERA,35784.0,652.755729,848.712008,24.0,183.0,328.0,689.0,7954.0
CH04,35784.0,1.530153,0.499097,1.0,1.0,2.0,2.0,2.0
CH06,35784.0,44.108959,19.242213,15.0,28.0,42.0,59.0,101.0
CH07,35781.0,3.184595,1.650362,1.0,2.0,3.0,5.0,5.0
CH08,35784.0,2.098536,1.790486,1.0,1.0,1.0,4.0,23.0
NIVEL_ED,35784.0,3.891152,1.443251,1.0,3.0,4.0,5.0,7.0
ESTADO,35725.0,1.861190,0.971700,1.0,1.0,1.0,3.0,3.0
CAT_OCUP,20663.0,2.684363,0.543234,1.0,2.0,3.0,3.0,4.0
EMPLEO,19679.0,1.443976,0.496864,1.0,1.0,1.0,2.0,2.0
SECTOR,18939.0,1.387982,0.616812,1.0,1.0,1.0,2.0,3.0
PP04C,16995.0,4.804825,3.782961,0.0,1.0,4.0,8.0,12.0
PP04D_COD,19672.0,44919.554392,22978.095458,1.0,30203.0,41332.0,57314.0,99998.0
P21,15134.0,859946.532245,593698.091972,3000.0,400000.0,800000.0,1200000.0,3000000.0
P47T,22527.0,787854.525680,546580.526275,700.0,390000.0,650000.0,1000000.0,2900000.0
PP07H,13941.0,1.367692,0.482194,1.0,1.0,1.0,2.0,2.0
PP3E_TOT,19645.0,35.907050,16.315336,0.0,25.0,40.0,48.0,120.0

Con el objetivo de garantizar la robustez del análisis estadístico, se procedió a la detección y depuración de outliers e inconsistencias en las variables de interés. En primer lugar, se aplicó un filtro de edad para trabajar exclusivamente con la Población en Edad de Trabajar (≥15 años). Posteriormente, para las variables de ingresos (P21 y P47T), se eliminaron valores iguales o menores a cero y se aplicó un recorte en el percentil 99 de la distribución para mitigar el sesgo introducido por valores extremos que no reflejan la realidad promedio de los trabajadores. Finalmente, respecto a la variable de horas trabajadas (PP3E_TOT), se descartaron registros superiores a las 120 horas semanales por resultar físicamente inviables, asegurando así la integridad de los estimadores salariales y la comparabilidad de los resultados entre los períodos analizados.

In [18]:
#Para 2024, como ya limipiamos la base, tomamos como "respondieron" a todos aquellos que tengan valores no nulos
respondieron_2024 = T424_v[T424_v['ESTADO'].notna()].copy()
norespondieron_2024 = T424_v[T424_v['ESTADO'].isna()].copy()

#Para 2025
respondieron_2025 = T425_v[T425_v['ESTADO'].notna()].copy()
norespondieron_2025 = T425_v[T425_v['ESTADO'].isna()].copy()

In [19]:
#De quienes respondieron para cada año, nos quedamos solamente con los ocupados y creamos la subbase OCUPADOS
ocupados_2024 = respondieron_2024[respondieron_2024['ESTADO'] == 1].copy()
ocupados_2025 = respondieron_2025[respondieron_2025['ESTADO'] == 1].copy()